aws-region        = "us-east-1"
ami_users         = ["999859291911", "741600036362"]
instance_type     = "t2.micro"
source_ami        = "ami-0dfcb1ef8550277af"
ssh_username      = "ec2-user"
device_name       = "/dev/xvda"
volume_type       = "gp2"
volume_size       = 8
file_sources_list = ["./packer/cloudwatch_config.json", "/home/runner/work/webapp/webapp/release.zip"]
shell_sources     = ["./packer/setup_cloudwatch.sh", "./packer/env_setup.sh"]